/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package com.konfirmagi.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 5;
  /** RegularExpression Id. */
  int QUIT = 6;
  /** RegularExpression Id. */
  int CODE = 7;
  /** RegularExpression Id. */
  int SPACE = 8;
  /** RegularExpression Id. */
  int RESULT = 9;
  /** RegularExpression Id. */
  int EQUALS = 10;
  /** RegularExpression Id. */
  int DIGIT = 11;
  /** RegularExpression Id. */
  int SIGN = 12;
  /** RegularExpression Id. */
  int BROPEN = 13;
  /** RegularExpression Id. */
  int BRCLOSE = 14;
  /** RegularExpression Id. */
  int ID = 15;
  /** RegularExpression Id. */
  int LETTER = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"^\"",
    "<QUIT>",
    "\"200\"",
    "\" \"",
    "\"result\"",
    "\"=\"",
    "<DIGIT>",
    "\"-\"",
    "\"(\"",
    "\")\"",
    "<ID>",
    "<LETTER>",
  };

}
